'use client';
import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import styles from '../styles/sub.module.scss';
import Layout from './sub_layout';
import { useRouter } from 'next/router';
import Head from 'next/head';
import PageLoading from '../components/pageLoading';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger';
import Curve from '@/components/Layout/index';
// import { slideUp } from './slideup';
import { motion } from 'framer-motion';

export default function About() {
  const overImg = useRef(null);
  const aboutTxt = useRef(null);
  const router = useRouter();
  let mm = gsap.matchMedia();

  useEffect(() => {
    const handleRouteChange = (url, { shallow }) => {
      setTimeout(() => {
        mm.kill();
      }, 500);
    };
    router.events.on('routeChangeStart', handleRouteChange);

    gsap.registerPlugin(ScrollTrigger);

    mm.add('(min-width: 1000px)', () => {
      gsap.to(aboutTxt.current, {
        scrollTrigger: {
          trigger: document.documentElement,
          scrub: 0.5,
          start: 0,
          //end: '+=100%',
        },
        y: '200px',
      });

      gsap.to(overImg.current, {
        scrollTrigger: {
          trigger: document.documentElement,
          scrub: 0.5,
          start: 0,
          //end: '+=100%',
        },
        y: '-500px',
      });
    });

    mm.add('(max-width: 999px)', () => {
      gsap.to(aboutTxt.current, {
        scrollTrigger: {
          trigger: document.documentElement,
          scrub: 0.5,
          start: 0,
          //end: '+=100%',
        },
        y: '-30px',
      });

      gsap.to(overImg.current, {
        scrollTrigger: {
          trigger: document.documentElement,
          scrub: 0.5,
          start: 0,
          //end: '+=100%',
        },
        y: '-160px',
      });
    });

    let timeOutFunctionId;
    function workAfterResizeIsDone() {
      ScrollTrigger.refresh();
    }
    window.addEventListener('resize', function () {
      clearTimeout(timeOutFunctionId);
      timeOutFunctionId = setTimeout(workAfterResizeIsDone, 200);
    });
  }, []);
  return (
    <>
      {/* <PageLoading /> */}
      <Head>
        <title>ABOUT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Curve>
        <motion.div className={styles.container}>
          <h2 className={styles.subTit}>Helping brands thrive in the digital world</h2>
          {/* <div style={{ height: '500px' }}></div> */}
          <div className={styles.about}>
            <div className={styles.aboutTxt} ref={aboutTxt}>
              I help companies from all over the world with tailor-made solutions. With each project, I push my work to
              new horizons, always putting quality first.
            </div>
            <div className={styles.overWrap}>
              <div className={styles.over} ref={overImg}></div>
            </div>
          </div>
          <div style={{ height: '1000px', background: 'yellow' }}>aaa</div>
        </motion.div>
      </Curve>
    </>
  );
}
