"use client";
import { useEffect, useLayoutEffect, useRef, useState } from "react";
import styles from "@/styles/sub.module.scss";
import Layout from "./sub_layout";
import Head from "next/head";
import PageLoading from "../components/pageLoading";

export default function About() {
  const [aa, aaa] =useState(false);

  useEffect(()=>{
    
  })


  return (
    <>
      <PageLoading />
      <Layout>
        <Head>
          <title>ABOUT</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <section className={styles.section}>
          <h2>ABOUT</h2>
          <div>
            <button type="button" onClick={()=>{
              aaa(!aa)
            }} className={`${aa ? styles.test : ""}`}>button</button>
            {
              aa && <p>open test</p>
            }
          </div>
          <ul>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
            <li>Helping brands thrive in the digital world</li>
          </ul>
        </section>
      </Layout>
    </>
  );
}
