'use client';
import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger';
import { AnimatePresence } from 'framer-motion';
import Header from '../components/Header';
import Preloader from '../components/Preloader';
import Landing from '../components/Landing';
import About from '../components/About';
import Projects from '../components/Projects';
import SlidingImages from '../components/SlidingImages';
import Contact from '../components/Contact';
import { useRouter } from 'next/router';

// import { ScrollTrigger } from "gsap/ScrollTrigger";

export default function Home() {
  const nameInput = useRef(null);
  const router = useRouter();

  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    (async () => {
      setTimeout(() => {
        setIsLoading(false);
        document.body.style.cursor = 'default';
        window.scrollTo(0, 0);
      }, 2000);
    })();

    const handleRouteChange = (url, { shallow }) => {
      document.body.classList.add('main_hidden');
      setTimeout(() => {
        document.body.classList.remove('main_hidden');
      }, 500);
    };

    router.events.on('routeChangeStart', handleRouteChange);

    // If the component is unmounted, unsubscribe
    // from the event with the `off` method:
    return () => {
      router.events.off('routeChangeStart', handleRouteChange);
    };
  }, []);

  // useLayoutEffect(() => {
  //   gsap.registerPlugin(ScrollTrigger);
  //   gsap.to(nameInput.current, 1, {
  //     x: 45,
  //     rotation: 50,

  //     scrollTrigger: {
  //       trigger: nameInput.current,
  //       start: "center 50%",
  //       end: "bottom 50%",
  //       markers: false,
  //       pin: false,
  //       scrub: 2,
  //       ease: "power3.inOut",
  //     },
  //   });
  // });
  return (
    <>
      <Head>
        <title>메인페이지</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AnimatePresence mode="wait">{isLoading && <Preloader />}</AnimatePresence>
      {/* <Header /> */}
      <Landing />
      <About />
      <Projects />
      <SlidingImages />
      <Contact />
    </>
  );
}
